export const STATE = {
  health: null,
  status: null,
  report: null,
  stress: null,
  groups: null,
  cumulativePnl: null,
  aprSeries: null,
  portfolioSnapshot: null,
  dataFreshness: { source: null, snapshotMs: null, statusMs: null, live: false },
  chartsDataLoaded: false,
  chartsLoadInFlight: false,
  bookFilter: "ALL",
  aprWindow: 30,
  charts: {},
  autoRefreshHandle: null,
  refreshInFlight: false,
  investorReady: false,
  investorLoadTotal: 0,
  investorLoadDone: 0,
  lastRefreshStartedMs: 0,
  statusErrorOnce: false,
  lastUnderlyingIndexUsd: {},
  lastSpotUsd: { BTC: null, ETH: null },
  activityOpenPage: 1,
  activityClosedPage: 1,
};
