export const STATE = {
  health: null,
  status: null,
  report: null,
  stress: null,
  groups: null,
  /** Investor: disk groups shown; live Deribit bundle still enriching open marks. */
  groupsLivePending: false,
  cumulativePnl: null,
  cumulativeSpotPnl: null,
  aprSeries: null,
  portfolioSnapshot: null,
  dataFreshness: {
    source: null,
    snapshotMs: null,
    statusMs: null,
    live: false,
    cacheSavedAt: null,
    cacheAgeMs: null,
  },
  chartsDataLoaded: false,
  chartsLoadInFlight: false,
  /** Shared promise while chart APIs / vendor load; coalesces toggle + refresh callers. */
  chartsLoadPromise: null,
  stressDataLoaded: false,
  stressLoadInFlight: false,
  transfers: null,
  transfersLoadError: null,
  transfersDataLoaded: false,
  transfersLoadInFlight: false,
  bookFilter: "ALL",
  aprWindow: 30,
  charts: {},
  autoRefreshHandle: null,
  refreshInFlight: false,
  summaryLoadPending: false,
  summaryLoadInFlight: false,
  investorReady: false,
  investorLoadTotal: 0,
  investorLoadDone: 0,
  /** Set when beginInvestorLoad runs; gates overlay dismiss until paint + min time. */
  investorLoadStartedMs: 0,
  investorLoadDismissAllowed: false,
  lastRefreshStartedMs: 0,
  lastRefreshMs: 0,
  statusErrorOnce: false,
  lastUnderlyingIndexUsd: {},
  lastSpotUsd: { BTC: null, ETH: null },
  lastPriceChangePct24h: { BTC: null, ETH: null },
  lastIvRankPct: { BTC: null, ETH: null },
  lastDvol: { BTC: null, ETH: null },
  ivRankLookbackDays: null,
  activityOpenPage: 1,
  activityClosedPage: 1,
  /** Set by refresh.registerRenderDashboard for late async API completions. */
  dashboardRenderHook: null,
};
