export const STATE = {
  health: null,
  status: null,
  report: null,
  stress: null,
  groups: null,
  cumulativePnl: null,
  aprSeries: null,
  portfolioSnapshot: null,
  dataFreshness: { source: null, snapshotMs: null, statusMs: null, live: false },
  chartsDataLoaded: false,
  chartsLoadInFlight: false,
  /** Shared promise while chart APIs / vendor load; coalesces toggle + refresh callers. */
  chartsLoadPromise: null,
  stressDataLoaded: false,
  stressLoadInFlight: false,
  bookFilter: "ALL",
  aprWindow: 30,
  charts: {},
  autoRefreshHandle: null,
  refreshInFlight: false,
  summaryLoadPending: false,
  summaryLoadInFlight: false,
  investorReady: false,
  investorLoadTotal: 0,
  investorLoadDone: 0,
  lastRefreshStartedMs: 0,
  statusErrorOnce: false,
  lastUnderlyingIndexUsd: {},
  lastSpotUsd: { BTC: null, ETH: null },
  activityOpenPage: 1,
  activityClosedPage: 1,
  /** Set by refresh.registerRenderDashboard for late async API completions. */
  dashboardRenderHook: null,
};
